<x-tasks.rmsinstall.details.meterinfo
    :$task
    :$meterSerialNumber
/>
<x-tasks.rmsinstall.details.regulatorinfo
    :$task
    :$regulatorSerialNumber
/>
<x-tasks.rmsinstall.details.usedmaterials
    :$task
    :$addMaterialForm
    :$deleteMaterialForm
    :$materialCode
    :$quantity
/>
