<div>
    <x-ui.topbar/>
    <x-user.edit.buttons/>
    <x-ui.title title="Users Details"/>
    <x-user.edit.information
        :$user
        :$userStatusForm
        :$userPhotoForm
        :$userValueChangeForm
        :$photos
        :$pic
        :$userSignatureForm
    />
    @if($userValueChangeForm)
        @teleport('body')
        <x-form.form-modal
            :$formTitle
            formId="changeUserValueForm"
            formCondition="userValueChangeForm"
            :submitCondition="true"
            :$submitFun
            submitIcon="refresh"
            submitTag="Update"
        >
            <x-form.inputwire
                :name="$field"
                :$placeholder
                :$icon
            />
        </x-form.form-modal>
        @teleport('body')
    @endif
</div>
