@if($userSignatureForm)
    @teleport('body')
    <x-form.form-modal
        formTitle="Change Signature"
        formId="changeUserSignatureForm"
        formCondition="userSignatureForm"
        :submitCondition="true"
        submitFun="updateSignature"
        submitIcon="refresh"
        submitTag="Update"
        enctype="multipart/form-data"
    >
        <x-form.upload-photo
            :$user
            :$pic
            wireSubmit="updateSignature"
            :$src
        />
    </x-form.form-modal>
    @teleport('body')
@endif
